#define ID_WINDOW                   10
#define ID_QUIT                     11
#define ID_ABOUT                    12
#define ID_ASSOCTYPES               13
#define ID_ASSOCFILTERS             14
#define ID_HELPINDEX                15
#define ID_GENERALHELP              16
#define ID_KEYSHELP                 17
#define ID_USINGHELP                18
#define ID_HELPPRODUCTINFO          19

#define EAS_HELP_TABLE              40
#define SUBTABLE_MAIN               41
#define SUBTABLE_ASSOCDLG           42
#define SUBTABLE_ADDHANDLEDLG       43
#define SUBTABLE_ADDASSOCDLG        44

#define ID_ABOUTDLG                 100
#define ID_ABOUTICON                103
#define ID_ASSOCDLG                 200
#define ID_ASSOCLIST                201
#define ID_ASSOC                    202
#define ID_DELASSOC                 204
#define ID_DELHANDLE                205
#define ID_ADDHANDLE                206
#define ID_DEFAULT                  207
#define ID_ADDASSOCDLG              300
#define ID_ADDASSOC                 208
#define ID_NEWTYPE                  301
#define ID_ADDHANDLEDLG             400
#define ID_TYPEPROG                 402
#define ID_TYPEOBJ                  403
#define ID_OBJECTLIST               404
#define ID_NEWPROG                  405
#define ID_TEXTPROG                 406
#define ID_TEXTOBJ                  407

